version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql_container
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE:  shivdb
    ports:
      - '3307:3306'
    volumes:
      - mysql-backup:/var/lib/mysql

  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-test-app:1.0.0
    depends_on:
      - mysql-db
    ports:
      - '7575:8081'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-db:3306/shivdb'
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password


volumes:
  mysql-backup: